### PR TITLE
fix(#769): adjust the position of the media preview clear button.

### LINKED ISSUE #769: "X" button rendered outside the image/video preview container
### Expected Behaviour

The "X" (delete/remove) button should be positioned inside the media preview container for the image and video upload question type, to maintain a cohesive UI and clear visual association with the file.

Note that the audio question type renders the "X" on the right side outside the audio player; this remains unchanged. 

### Observed Behaviour

The "X" button is appearing outside the image/video preview container. This creates a disconnected appearance.

### Reproduction Steps

Form (XML or XLSX file): All question types form

Steps:

1. Open a web form containing a mandatory image upload field.
2. Click the "Choose image" button and upload any image file.
3. Observe the placement of the "X" button once the thumbnail preview is displayed.

### Screenshots or Videos

Image

### Environment

- Browser version: Chrome
- OS: MacOS
- Web Forms version: 0.23

### PR DESCRIPTION
**Pull request by latin-panda**
Closes #769

### I have verified this PR works in these browsers (latest versions):

- [x] Chrome
- [x] Firefox
- [x] Safari (macOS)
- [ ] Safari (iOS)
- [x] Chrome for Android
- [ ] Not applicable

### What else has been done to verify that this works as intended?

https://github.com/user-attachments/assets/8e69a251-31dd-4318-b576-e96c99530085

### CODE REVIEW

**Comment by latin-panda** [comment]
@garethbowen This is ready for review; I'll send it first for a quick QA verification.

**Comment by latin-panda** [comment]
It has passed QA verification :) Ready for review

**Comment by garethbowen** [comment]
Comment on issue - IMO this is not a bug. Waiting for design confirmation.

File: packages/web-forms/src/components/form-elements/upload/UploadControl.vue [hunk 1]
```diff
@@ -181,7 +181,13 @@ const onDrop = (event: DragEvent) => {
...
 						<UploadFilePreview :file-name="fileName" />
 					</template>
-					<Button v-if="!isDisabled" severity="secondary" outlined class="clear-button" @click="clearValue">
+					<Button
+						v-if="!isDisabled"
+						:class="{ 'over-preview': fileType === 'image' || fileType === 'video' }"
+						severity="secondary"
+						outlined
+						class="clear-button"
+						@click="clearValue">
```
Comment (garethbowen) [inline packages/web-forms/src/components/form-elements/upload/UploadControl.vue]: This is triggering the lint warning below...

**Review by garethbowen — APPROVED** [review]
Looks good!

There's a lint warning (not error) being generated - commented below.

File: packages/web-forms/src/components/form-elements/upload/UploadControl.vue (hunk 1 above)
Comment (latin-panda) [reply packages/web-forms/src/components/form-elements/upload/UploadControl.vue]: Thanks! Fixed!
