### PR TITLE
fix(#679): prevent showing input errors when starting new submissions

### LINKED ISSUE #679: Required error message in the new instance of a sent submission
#### Problem description
After submitting a form the required error message appears in the new instance. It seems that the required error message appears not only after violating the required question but also when another constraint was violated while filling a form (see RequiredAndConstraint form).

#### URL of the page
e.g. https://staging.getodk.cloud/projects/204/forms/geoshapeTraceFieldListRequired/submissions

https://staging.getodk.cloud/projects/204/forms/RequiredAndConstraint/submissions
#### Steps to reproduce the problem
1. Open a form with a required question (example in the URL).
2. Try to send the form without filling the required question.
3. Fill the required questions.
4. Send the submission.

Another way:
1. Open the RequiredAndConstraint form.
2. Fill the required questions.
3. In Constraint question enter 10 (it violates the constraint).
4. Change the values to e.g. 5.
5. Send the submission.
#### Screenshot
https://jam.dev/c/a42107ea-08ad-4fa3-ba20-e4da4cc88ff9

#### Expected behavior
The error message shouldn't appear.
#### Web Forms version
v0.19.0 (also v0.18.2 on test.getodk.cloud)
#### Browser version
Chrome and Firefox

### PR DESCRIPTION
**Pull request by latin-panda**
Closes #679

### I have verified this PR works in these browsers (latest versions):

- [x] Chrome
- [ ] Firefox
- [ ] Safari (macOS)
- [ ] Safari (iOS)
- [ ] Chrome for Android
- [ ] Not applicable

### What else has been done to verify that this works as intended?

<details><summary>Regression testing of geopoint in edit mode - All geopoint are placement-map</summary>

https://github.com/user-attachments/assets/6c305089-9d5d-46fa-94d0-8ea4a0040c2c

</details>

<details><summary> Second round of testing form errors after latest changes</summary>

https://github.com/user-attachments/assets/e4a48a96-fc13-4e80-98e0-d91156a4b18b

</details>

<details><summary> First round of testing</summary>

https://github.com/user-attachments/assets/513a91b6-3b9e-48a4-8800-3f41af2dfffe

</details>

### What's changed
- Adds a reset function to clear some properties of ODKWebForm component.

### CODE REVIEW

File: packages/web-forms/src/components/OdkWebForm.vue [hunk 1]
```diff
@@ -324,7 +336,7 @@ onUnmounted(() => {
 		<div class="powered-by-wrapper">
 			<a class="anchor" href="https://getodk.org" target="_blank">
 				<span class="caption">Powered by</span>
-				<img class="logo" src="../assets/images/odk-logo.svg" alt="ODK">
+				<img class="logo" src="../assets/images/odk-logo.svg" alt="ODK" />
```
Comment (garethbowen) [inline packages/web-forms/src/components/OdkWebForm.vue]: There's a lint warning on this line, which should just be reverted I think?
