### PR TITLE
fix(#671, #676): fixes spacing in map status bar and updates tooltip text

### LINKED ISSUE #671: UI breaks on mobile when Longitude and Latitude are added.
### Expected Behaviour

UI should not break

### Observed Behaviour

Icon for polygon is to close to the text on mobile when Longitude and Latitude are added.

### Reproduction Steps

Steps:
1. Open link https://staging.getodk.cloud/projects/202/forms/geofence_example/submissions
2. Click on the New Submission
3. In the map view click on one of the placed points

### Screenshots or Videos

Image

### Environment

- Device: iPhone 12 Pro
- OS: IOS 26.3
- Web Forms version: v0.19.0

### Additional Context

### LINKED ISSUE #676: "Zoom to fit all options" tooltip text for fit tool on maps is not always appropriate
### Description
The tooltip text for the fit tool below expand screen and above current location is "zoom to fit all options". I think that is because it was first built for select one from map. 

Proposed change: update text to "zoom to fit" which makes sense in all mapping contexts

### PR DESCRIPTION
**Pull request by latin-panda**
Closes #671
Closes #676

### I have verified this PR works in these browsers (latest versions):

- [x] Chrome
- [ ] Firefox
- [ ] Safari (macOS)
- [ ] Safari (iOS)
- [ ] Chrome for Android
- [ ] Not applicable

### What's changed
- Updates tooltip text
- Prevents icons from shrinking
- Adds gap between text and buttons in map's status bar

### CODE REVIEW

File: packages/web-forms/src/components/common/map/MapControls.vue [hunk 1]
```diff
@@ -29,7 +29,7 @@ const emit = defineEmits([
 			<!-- TODO: translations -->
 			<button
 				class="zoom-fit-all"
-				title="Zoom to fit all options"
+				title="Zoom to fit"
```
Comment (latin-panda) [inline packages/web-forms/src/components/common/map/MapControls.vue]: @alyblenkin Since I need to make a release to push a bug fix, I decided to just fix this too.
Is the text okay? "Zoom to fit"
