### PR TITLE
fix(#586): defer parsing of translation elements

### LINKED ISSUE #586: Defer parsing of translations until needed
### Description

During form load we do some parsing of translation elements which can be deferred until its needed. This is particularly beneficial if the form has multiple languages because we should only do work on the language that's being used currently.

More information on Drive: https://docs.google.com/document/d/1lTDaNY2Qg9kbn1jf0zBKxy_tqEUrgSrrl3P_bZ4fxw0/edit

---

### Checklist
- **Does it need UI/UX design?**
  - [ ] Yes. Describe the UI/UX requirements or attach a Figma link in the "Design" section.
  - [x] No
- **Does it need API design?**
  - [ ] Yes. Specify the endpoints, methods, or data structures needed.
  - [x] No
- **Does it need design around state flow?**
  - [ ] Yes. Outline the state flow requirements.
  - [x] No
- **Does it need a test plan?**
  - [ ] Yes. Add the test plan as a comment in this task or attach the document.
  - [x] No
---

### PR DESCRIPTION
**Pull request by garethbowen**
Closes #586

### I have verified this PR works in these browsers (latest versions):

- [ ] Chrome
- [x] Firefox
- [ ] Safari (macOS)
- [ ] Safari (iOS)
- [ ] Chrome for Android
- [ ] Not applicable

### What else has been done to verify that this works as intended?

- CI
- Performance testing: https://docs.google.com/document/d/1lTDaNY2Qg9kbn1jf0zBKxy_tqEUrgSrrl3P_bZ4fxw0/edit

### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Shouldn't

### CODE REVIEW

File: packages/xforms-engine/src/instance/text/markdownFormat.ts [hunk 1]
```diff
@@ -208,7 +208,8 @@ function toOdkMarkdown(str: string): MarkdownNode[] {
 }
 
 export function format(chunks: readonly TextChunk[]): MarkdownNode[] {
-	outputStrings = new Map<string, string>();
 	const str = escapeEditableChunks(chunks);
-	return toOdkMarkdown(str);
+	const result = toOdkMarkdown(str);
+	outputStrings.clear();
```
Comment (garethbowen) [inline packages/xforms-engine/src/instance/text/markdownFormat.ts]: By clearing after the fact the output strings aren't kept in memory longer than necessary.

Also it saves on creating a new map.

File: packages/xforms-engine/src/lib/reactivity/text/createTextRange.ts [hunk 2]
```diff
@@ -17,57 +20,84 @@ interface ChunksAndMedia {
...
+		// only translations have 'nodes' chunks
+		return definition.chunks as Array<TextChunkExpression<'string'>>;
+	}
+	const itextId = context.evaluator.evaluateString(definition.chunks[0].toString()!, {
+		contextNode: context.contextNode,
+	});
+	const lang = context.getActiveLanguage();
+	const elem = definition.form.model.getItextElement(lang, itextId);
+	return elem ? generateChunksForTranslation(elem) : [];
+};
```
Comment (garethbowen) [inline packages/xforms-engine/src/lib/reactivity/text/createTextRange.ts]: This code has been moved here from the parsing step. By only chunking the translations for the active language we save a bunch of work for languages that may never be loaded.

File: packages/xforms-engine/src/parse/model/TranslationDefinitionMap.ts [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+export class TranslationDefinitionMap extends Map<string, Map<string, Element>> {
+	constructor(translationElements: readonly DOMItextTranslationElement[]) {
+		super(
+			translationElements.map((translationElement) => {
+				const lang = translationElement.getAttribute('lang');
+				return [lang, generateChunksForLanguage(translationElement)] as const;
+			})
+		);
+	}
+}
```
Comment (garethbowen) [inline packages/xforms-engine/src/parse/model/TranslationDefinitionMap.ts]: This file was renamed because now it's a lot simpler. I tried removing this altogether but it turned out that it was expensive to look the element up by ID so keeping the map sped up looking up the element which more than made up for the initial load.
