### PR TITLE
fix(#460): long labels in list table

### LINKED ISSUE #460: Broken UI in form with styling
**Problem Description**
Broken UI in form with styling
Image

**Steps to reproduce the problem**
1. Open new submission: https://staging.getodk.cloud/projects/139/forms/color_test/submissions
2. Or Upload form:  [color_test.xml.txt](https://github.com/user-attachments/files/21411749/color_test.xml.txt) To new project, change settings to WebForms and start new submission

**Expected Behavior:**
Not broken UI

**Browser**
Firefox 136.0 (64-bit)
Chrome 130.0.6723.69 (64-bit)

**Central version:**
https://github.com/getodk/central/commit/b9e6f488e99286d263b24b17f91423a81fab384c (v2025.2.0-3-gb9e6f48)
19438df85e11e3159043536895ab6ea620c78888 client (v2025.2.0-1-g19438df8)
6d811d77c08d493e0854bc02361b93044e438e60 server (v2025.2.0-7-g6d811d77)

### PR DESCRIPTION
**Pull request by latin-panda**
Closes #460

### I have verified this PR works in these browsers (latest versions):

- [x] Chrome
- [x] Firefox
- [x] Safari (macOS)
- [ ] Safari (iOS)
- [ ] Chrome for Android
- [ ] Not applicable

### What else has been done to verify that this works as intended?

Test video:

https://github.com/user-attachments/assets/90fa491b-8769-4a9f-bfef-a2d57f41da97

### What's changed
- Labels (the first column in each row) use 35% and options evenly divide up the rest on a wide screen for both Desktop and Mobile
- Prevents selecting options when `label` appearance is present

### CODE REVIEW

**Comment by lognaturel** [comment]
This helps the narrow issue described in the issue but I don't think it goes quite far enough to help make these appearances useful! 

See https://github.com/getodk/web-forms/issues/179 for more. The intent for these appearances is to create a table. The column labels (Jessica, Jaune, Vert) should not overlap with the row labels (Pregnancy, Post-partum). The radio buttons should have the same alignment and take up the same width as the column labels. Labels only should not be selectable. 

Maybe this PR could additionally:
* make it so labels (the first column in each row) use 35% and options evenly divide up the rest on a wide screen and 50% each for labels and options for narrow screens (match Collect)
* apply the same styling for the label and list-nolabel appearances so labels and options line up

What do you think?

**Comment by latin-panda** [comment]
I'll get back to this on Monday. I need to see it working and validate the readability with Aly.

File: packages/web-forms/src/components/common/CheckboxWidget.vue [hunk 1]
```diff
@@ -13,6 +13,9 @@ defineEmits(['update:modelValue', 'change']);
 const props = defineProps<CheckboxWidgetProps>();
 
 const selectValues = (values: readonly string[]) => {
+	if (props.question.appearances.label) {
```
Comment (lognaturel) [inline packages/web-forms/src/components/common/CheckboxWidget.vue:16]: Feels like it'd be great to share that logic between select one and multiple. But that can be for another time!

**Review by lognaturel — APPROVED** [review]
Big improvements!

**Comment by lognaturel** [comment]
A note for QA: it's most common to have labels on the left without hints.

Here are a couple of forms to consider:
* [Testing form for `table-list`](https://docs.google.com/spreadsheets/d/12b_w0G9vAoh61O5CpT2qIdcNKeSiF5jLvHQtWWTSMDY/edit?gid=1068911091#gid=1068911091)
* [COVID-19 case report](https://docs.google.com/spreadsheets/d/16HxHDqA39cvlS7MaduWBpUpvnnlT0kcmn3UYQnmbbVk/edit?gid=0#gid=0)

File: packages/web-forms/src/components/common/CheckboxWidget.vue (hunk 1 above)
Comment (latin-panda) [reply packages/web-forms/src/components/common/CheckboxWidget.vue:16]: This morning, I am considering that when it's `labels` appearance, it should render simple text and not use radio or checkboxes (and we delete this condition). I will open a ticket for that improvement; it will require a bit CSS work.

**Comment by srujner** [comment]
**Tested with Success!**

**Verified cases on Google Chrome and Mobile Devices (Samsung Galaxy M23 and Iphone 12 Pro);** 
- Responsiveness of the labels in Web Forms
- Regression check on forms listed above;
- Issue is no longer reproducing; 
- Label-only rows are not interactive/selectable.
- No console errors related to layout or interactivity.
- Also checked forms with hints and nested repeats.

**Things I found during testing;** 

<details> <summary> 1. In the select Grids or Question Grid forms the radio buttons and text is going outside the table in the vertical view, horizontal works fine</summary>

bug1

</details>

<details> <summary> 2. On Dominika's device there was a different default zoom level which causes form to display with cuted off text (Name at the left side on the screenshot), after zooming out it looks alright. But it looks like different devices have different zoom level set as default? Probably worth to discuss it</summary>

Screenshot_2025-08-27-16-01-43-840_com android chrome

</details>
